# Generated by Django 5.2.13 on 2026-04-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(blank=True, max_length=120)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('isp', models.CharField(blank=True, max_length=255)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('search_type', models.CharField(choices=[('basic', 'Basic Search'), ('advanced', 'Advanced Search')], db_index=True, max_length=20)),
                ('query', models.TextField(blank=True)),
                ('court_location', models.CharField(blank=True, max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Search Analytics Record',
                'verbose_name_plural': 'Search Analytics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='search_api__ip_addr_3745f7_idx'), models.Index(fields=['country', 'timestamp'], name='search_api__country_50a2b8_idx')],
            },
        ),
    ]
